#!/bin/bash

set +u -eo pipefail

{
  echo "MYSQL_HOST=${MYSQL_HOST}"
  echo "MYSQL_USERNAME=${MYSQL_USERNAME}"
  echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
  echo "ACR_LOGIN_SERVER=${ACR_LOGIN_SERVER}"
  echo "ACR_USERNAME=${ACR_USERNAME}"
  echo "ACR_PASSWORD=${ACR_PASSWORD}"
  echo "TENANT_ID=${TENANT_ID}"
  echo "CLIENT_ID_KEYVAULT=${CLIENT_ID_KEYVAULT}"
  echo "CLIENT_SECRET_KEYVAULT=${CLIENT_SECRET_KEYVAULT}"
} >> "$GITHUB_ENV"